### ISSUE TITLE
Make --click=first to be default

### ISSUE THREAD

**Issue by mgrouch** [Plippo/twofing#10]
Usually a user wants to aim at something directly.
(Example adding a waypoint on a chartplotter)
So having --click=first default makes more sense.

Thanks

**Comment by Plippo** [comment]
In my experience, --click=first makes it harder to aim with your fingers because if you are touching the screen with both fingers at the same time, it is a matter of luck which one is regarded as the first and which one as the second. Using the current default of --click=center, you can simply position your fingers in such a way that the target is between them and get a consistent result. Using --click=first, you are not able to touch the screen with both fingers at the same time, but have to press one first and then the other. This makes using the screen slower.

**Comment by mgrouch** [comment]
Thanks. It’s fine with me as long as there is an option to configure it 
with click=first. Default can be as is.
